schema_version: 1

context:
  name: brisc
  version: "0.1.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6eb50bb4bfe09179af75ea7869153dd919b709afc711448be7a4096ac49eacda

build:
  number: 1
  script:
    interpreter: python
    content: |
      # Build without -Werror and /WX, so new compiler warnings don't fail
      # the build
      import os, pathlib, re, subprocess
      p = pathlib.Path('setup.py')
      s, n = re.subn(r"""['"](?:-Werror|/WX)['"][ \t]*,?[ \t]*""", '', p.read_text())
      assert n, 'no -Werror or /WX found in setup.py'
      p.write_text(s)
      subprocess.check_call([os.environ['PYTHON'], '-m', 'pip', 'install', '.',
                             '-vv', '--no-deps', '--no-build-isolation'])

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
    - cython >=3.0
    - numpy >=1.17.0
    - scipy >=0.16.0
    - if: osx
      then: llvm-openmp
    - if: x86_64
      then: libblas * *mkl
    - if: osx and arm64
      then: libblas * *newaccelerate
  run:
    - python
    - anndata
    - h5py
    - matplotlib-base >=3.5.0
    - numpy >=1.17.0
    - pandas
    - polars >=1.41.0
    - pyarrow >=0.17.0
    - r-seurat
    - ryp
    - scikit-misc
    - scipy >=0.16.0
    - if: osx
      then: llvm-openmp
    - if: x86_64
      then: libblas * *mkl
    - if: osx and arm64
      then: libblas * *newaccelerate

tests:
  - python:
      imports:
        - brisc

about:
  homepage: https://github.com/briscverse/brisc
  summary: Fast single-cell toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Wainberg
    - keon-arbabi
